### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by outbegin** [Feiyizhan/id-validator#9]
有的身份证解析会出问题 具体身份证号不便贴出
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at io.github.feiyizhan.idcard.IdCardUtils.getIdCardInfo(IdCardUtils.java:182)
	at com.xinyan.test.idvalidato.IdCardUtilsTests.main(IdCardUtilsTests.java:14)

**Comment by springwarms** [comment]
是地址没解析正确 抛的异常  作者能否修复下
